# Generated by Django 4.0.4 on 2022-05-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Course Type')),
                ('district', models.CharField(blank=True, max_length=1000, null=True, verbose_name='District')),
                ('type', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Type')),
                ('code', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Code')),
                ('college_short_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='College Short Name')),
                ('college_full_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='College Full Name')),
                ('course_code', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Course Code')),
                ('_1g', models.CharField(blank=True, max_length=1000, null=True, verbose_name='1G')),
                ('_1k', models.CharField(blank=True, max_length=1000, null=True, verbose_name='1K')),
                ('_1r', models.CharField(blank=True, max_length=1000, null=True, verbose_name='1R')),
                ('_2ag', models.CharField(blank=True, max_length=1000, null=True, verbose_name='2AG')),
                ('_2ak', models.CharField(blank=True, max_length=1000, null=True, verbose_name='2AK')),
                ('_2ar', models.CharField(blank=True, max_length=1000, null=True, verbose_name='2AR')),
                ('_2bg', models.CharField(blank=True, max_length=1000, null=True, verbose_name='2BG')),
                ('_2bk', models.CharField(blank=True, max_length=1000, null=True, verbose_name='2BK')),
                ('_2br', models.CharField(blank=True, max_length=1000, null=True, verbose_name='2BR')),
                ('_3ag', models.CharField(blank=True, max_length=1000, null=True, verbose_name='3AG')),
                ('_3ak', models.CharField(blank=True, max_length=1000, null=True, verbose_name='3AK')),
                ('_3ar', models.CharField(blank=True, max_length=1000, null=True, verbose_name='3AR')),
                ('_3bg', models.CharField(blank=True, max_length=1000, null=True, verbose_name='3BG')),
                ('_3bk', models.CharField(blank=True, max_length=1000, null=True, verbose_name='3BK')),
                ('_3br', models.CharField(blank=True, max_length=1000, null=True, verbose_name='3BR')),
                ('gm', models.CharField(blank=True, max_length=1000, null=True, verbose_name='GM')),
                ('gmk', models.CharField(blank=True, max_length=1000, null=True, verbose_name='GMK')),
                ('gmp', models.CharField(blank=True, max_length=1000, null=True, verbose_name='GMP')),
                ('gmr', models.CharField(blank=True, max_length=1000, null=True, verbose_name='GMR')),
                ('scg', models.CharField(blank=True, max_length=1000, null=True, verbose_name='SCG')),
                ('sck', models.CharField(blank=True, max_length=1000, null=True, verbose_name='SCK')),
                ('scr', models.CharField(blank=True, max_length=1000, null=True, verbose_name='SCR')),
                ('stg', models.CharField(blank=True, max_length=1000, null=True, verbose_name='STG')),
                ('stk', models.CharField(blank=True, max_length=1000, null=True, verbose_name='STK')),
                ('str', models.CharField(blank=True, max_length=1000, null=True, verbose_name='STR')),
                ('snq', models.CharField(blank=True, max_length=1000, null=True, verbose_name='SNQ')),
                ('_1h', models.CharField(blank=True, max_length=1000, null=True, verbose_name='1H')),
                ('_1kh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='1KH')),
                ('_1rh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='1RH')),
                ('_2ah', models.CharField(blank=True, max_length=1000, null=True, verbose_name='2AH')),
                ('_2akh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='2AKH')),
                ('_2arh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='2ARH')),
                ('_2bh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='2BH')),
                ('_2bkh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='2BKH')),
                ('_2brh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='2BRH')),
                ('_3ah', models.CharField(blank=True, max_length=1000, null=True, verbose_name='3AH')),
                ('_3akh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='3AKH')),
                ('_3arh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='3ARH')),
                ('_3bh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='3BH')),
                ('_3bkh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='3BKH')),
                ('_3brh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='3BRH')),
                ('gmh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='GMH')),
                ('gmkh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='GMKH')),
                ('gmrh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='GMRH')),
                ('sch', models.CharField(blank=True, max_length=1000, null=True, verbose_name='SCH')),
                ('sckh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='SCKH')),
                ('scrh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='SCRH')),
                ('sth', models.CharField(blank=True, max_length=1000, null=True, verbose_name='STH')),
                ('stkh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='STKH')),
                ('strh', models.CharField(blank=True, max_length=1000, null=True, verbose_name='STRH')),
            ],
        ),
    ]
