# Generated by Django 4.0.5 on 2022-06-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(blank=True, max_length=10000, null=True)),
                ('category', models.CharField(blank=True, max_length=1000, null=True)),
                ('code', models.CharField(blank=True, max_length=10000, null=True)),
                ('college', models.CharField(blank=True, max_length=10000, null=True)),
                ('course', models.CharField(blank=True, max_length=10000, null=True)),
                ('_1G', models.IntegerField(blank=True, null=True)),
                ('_1K', models.IntegerField(blank=True, null=True)),
                ('_1R', models.IntegerField(blank=True, null=True)),
                ('_2AG', models.IntegerField(blank=True, null=True)),
                ('_2AK', models.IntegerField(blank=True, null=True)),
                ('_2AR', models.IntegerField(blank=True, null=True)),
                ('_2BG', models.IntegerField(blank=True, null=True)),
                ('_2BK', models.IntegerField(blank=True, null=True)),
                ('_2BR', models.IntegerField(blank=True, null=True)),
                ('_3AG', models.IntegerField(blank=True, null=True)),
                ('_3AK', models.IntegerField(blank=True, null=True)),
                ('_3AR', models.IntegerField(blank=True, null=True)),
                ('_3BG', models.IntegerField(blank=True, null=True)),
                ('_3BK', models.IntegerField(blank=True, null=True)),
                ('_3BR', models.IntegerField(blank=True, null=True)),
                ('_GM', models.IntegerField(blank=True, null=True)),
                ('_GMK', models.IntegerField(blank=True, null=True)),
                ('_GMP', models.IntegerField(blank=True, null=True)),
                ('_GMR', models.IntegerField(blank=True, null=True)),
                ('_SCG', models.IntegerField(blank=True, null=True)),
                ('_SCK', models.IntegerField(blank=True, null=True)),
                ('_SCR', models.IntegerField(blank=True, null=True)),
                ('_STG', models.IntegerField(blank=True, null=True)),
                ('_STK', models.IntegerField(blank=True, null=True)),
                ('_STR', models.IntegerField(blank=True, null=True)),
                ('H_1G', models.IntegerField(blank=True, null=True)),
                ('H_1K', models.IntegerField(blank=True, null=True)),
                ('H_1R', models.IntegerField(blank=True, null=True)),
                ('H_2AG', models.IntegerField(blank=True, null=True)),
                ('H_2AK', models.IntegerField(blank=True, null=True)),
                ('H_2AR', models.IntegerField(blank=True, null=True)),
                ('H_2BG', models.IntegerField(blank=True, null=True)),
                ('H_2BK', models.IntegerField(blank=True, null=True)),
                ('H_2BR', models.IntegerField(blank=True, null=True)),
                ('H_3AG', models.IntegerField(blank=True, null=True)),
                ('H_3AK', models.IntegerField(blank=True, null=True)),
                ('H_3AR', models.IntegerField(blank=True, null=True)),
                ('H_3BG', models.IntegerField(blank=True, null=True)),
                ('H_3BK', models.IntegerField(blank=True, null=True)),
                ('H_3BR', models.IntegerField(blank=True, null=True)),
                ('H_GM', models.IntegerField(blank=True, null=True)),
                ('H_GMK', models.IntegerField(blank=True, null=True)),
                ('H_GMR', models.IntegerField(blank=True, null=True)),
                ('H_SCG', models.IntegerField(blank=True, null=True)),
                ('H_SCK', models.IntegerField(blank=True, null=True)),
                ('H_SCR', models.IntegerField(blank=True, null=True)),
                ('H_STG', models.IntegerField(blank=True, null=True)),
                ('H_STK', models.IntegerField(blank=True, null=True)),
                ('H_STR', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
